name: Develop

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm ci
      env:
        CI: true

    - name: Build
      run: npm run build --if-present
      env:
        CI: true

    - name: Test
      run: npm test --if-present
      env:
        CI: true